http:
  port: "8081"
  
american:
  host: "training4-american-api-higorcoliveira.us-e2.cloudhub.io"
  port: "80"
  basepath: "/"
  protocol: "HTTP"
  client_id: "c488d138dc3b4fe2a636943ac773889b"
  client_secret: "ac9efc09Cf2d45C39deDF7593BeBBA1f"
  
training:
  host: "mu.learn.mulesoft.com"
  port: "80"
  basepath: "/"
  protocol: "HTTP"

delta: 
  wsdl: "http://mu.learn.mulesoft.com/delta?wsdl"
  service: "TicketServiceService"
  port: "TicketServicePort"